language: node_js

os: linux

cache:
    directories:
      - node_modules

jobs:
    include:
      - name: Functional tests
        script: test/functional.sh
        node_js: 12
        cache:
            directories:
              - node_modules
              - terser-functional-tests

      - node_js: 10
        script: |
            node --require esm test/compress.js
            npm run test:mocha -- --require esm
        env:
          - TEST_NO_SANDBOX=1

      - node_js: 15
        env:
          - TERSER_TEST_ALL=1
        cache:
            directories:
              - node_modules
              - tmp
        before_script: npm run build

      - node_js: 15
        os: windows
        env:
          - TEST_NO_SANDBOX=1
        before_script: npm run build

